# -*- coding: utf-8 -*-
"""Stop looking at my dance face.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YMgNsfJKgK00DIZmgGdzMMVQWi6ZMn0d

Why do you keep looking at my dance face
"""

print("Keep dancing and stop looking at my dance face")
#i am able to do what i want to do
#i can not be stopped(comments, ignored by the PC)

#Variables
#String data type
Name_of_runner = "Okello"
#Integer data type
Height_of_runner = 175
#float data type
Distances_run = 42.195
#string data type
Favourite_shoe_brand = "Hoka"
#boolean data type
Is_the_runner_fast = True

# Now lets run these mfs
print("Name of runner: ",Name_of_runner)
print("Height of runnner: ",Height_of_runner)
print("Distances run: ",Distances_run)
print("Favourite shoe brand: ",Favourite_shoe_brand)
print("Is the runner fast: ",Is_the_runner_fast)

#Interactive script

Name_of_runner = input("What is your name: ")
print("Hello " + Name_of_runner + ", " + "I am honored to meet you!")
Year_of_birth = input("Which year were you born: ")
Current_year = 2025
Age = Current_year - int(Year_of_birth)
print("Your age is: ",Age)
print(Name_of_runner + ", " "Thank you for your struggle, You walked so that we could run. At over"" " + str(Age) + "years surely, you deserve to rest. Take care and Good bye for now")

Name_of_player = input("What is your name: ")
Year_of_birth = input("Which year were you born: ")
Current_year = 2025
Age = Current_year - int(Year_of_birth)
Out_put_message = "Hi, " + Name_of_player + " What an honour it has been to meet you, and to know that you are currently " + str(Age) + " years old, Please take care and see you later"
print(Out_put_message)

print(Out_put_message*12)



